### ISSUE TITLE
git cloning goreman just hangs

### ISSUE THREAD

**Issue by raoofm** [mattn/goreman#19] opened 2015-10-07 19:28 UTC
$ go get -u -v github.com/mattn/goreman
github.com/mattn/goreman (download)
github.com/daviddengcn/go-colortext (download)
github.com/joho/godotenv (download)
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag main.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)

**Comment by mattn** [comment] 2015-10-07 23:56
could you please try `go get -u -x github.com/mattn/goreman`.
use -x instead of -v.

**Comment by raoofm** [comment] 2015-10-08 13:07
@mattn 

$ get -u -x github.com/mattn/goreman
-bash: get: command not found
[rmohammed@weblogic-test-vm-01 ~]$ go get -u -x github.com/mattn/goreman
cd /var/home/rmohammed/gopath/src/github.com/mattn/goreman
git config remote.origin.url
cd /var/home/rmohammed/gopath/src/github.com/mattn/goreman
git symbolic-ref HEAD
cd /var/home/rmohammed/gopath/src/github.com/mattn/goreman
git pull --ff-only
cd /var/home/rmohammed/gopath/src/github.com/mattn/goreman
git show-ref
cd /var/home/rmohammed/gopath/src/github.com/mattn/goreman
git checkout master
cd /var/home/rmohammed/gopath/src/github.com/daviddengcn/go-colortext
git config remote.origin.url
cd /var/home/rmohammed/gopath/src/github.com/daviddengcn/go-colortext
git symbolic-ref HEAD
cd /var/home/rmohammed/gopath/src/github.com/daviddengcn/go-colortext
git pull --ff-only
cd /var/home/rmohammed/gopath/src/github.com/daviddengcn/go-colortext
git show-ref
cd /var/home/rmohammed/gopath/src/github.com/daviddengcn/go-colortext
git checkout master
cd /var/home/rmohammed/gopath/src/github.com/joho/godotenv
git config remote.origin.url
cd /var/home/rmohammed/gopath/src/github.com/joho/godotenv
git symbolic-ref HEAD
cd /var/home/rmohammed/gopath/src/github.com/joho/godotenv
git pull --ff-only
cd /var/home/rmohammed/gopath/src/github.com/joho/godotenv
git show-ref
cd /var/home/rmohammed/gopath/src/github.com/joho/godotenv
git checkout master
cd .
git clone https://gopkg.in/yaml.v2 /var/home/rmohammed/gopath/src/gopkg.in/yaml.v2

It hangs at this point

**Comment by raoofm** [comment] 2015-10-08 13:08
I think git is the issue at my end, I think I should verify git separately first.
Is git a dependency for goreman?

**Comment by raoofm** [comment] 2015-10-08 13:12
$ git clone https://gopkg.in/yaml.v2 /var/home/rmohammed/gopath/src/gopkg.in/yaml.v2
Initialized empty Git repository in /var/home/rmohammed/gopath/src/gopkg.in/yaml.v2/.git/

hangs here, if I run this individually

**Comment by mattn** [comment] 2015-10-08 13:33
Hmm, I can't reproduce it.

![](https://gyazo.com/10ab5943a047d85d0076d2660f467213.png)

**Comment by raoofm** [comment] 2015-10-08 13:35
$ git --version
git version 1.7.1

@mattn yours?

**Comment by mattn** [comment] 2015-10-08 14:09
git version 2.5.2 on windows.

**Comment by raoofm** [comment] 2015-10-08 14:35
ok let me try on windows and see

**Comment by wuyongxiu** [comment] 2016-08-04 09:58
@raoofm have you solved it? I encountered the same problem.

**Comment by raoofm** [comment] 2016-08-04 14:25
@wuyongxiu I forgot how I fixed it, it is almost an year. So I did a fresh install and don't see that issue again. It ran smoothly.

$ go version
go version go1.6.3 linux/amd64
$ git --version
git version 1.7.12.4

I see that there are a lot of fixes to goreman since this issue was opened.

I installed using  go get -u -x -v  github.com/mattn/goreman

Can you show some logs?

**Comment by wuyongxiu** [comment] 2016-08-05 01:06
@raoofm 
[kduser@v-app1-cloud ~]$ go version
go version go1.6.3 linux/amd64
[kduser@v-app1-cloud ~]$ git --version
git version 1.7.1

[kduser@v-app1-cloud ~]$ go get -u -x -v github.com/mattn/goreman
cd /home/kduser/go/src/github.com/mattn/goreman
git config remote.origin.url
github.com/mattn/goreman (download)
cd /home/kduser/go/src/github.com/mattn/goreman
git pull --ff-only
cd /home/kduser/go/src/github.com/mattn/goreman
git submodule update --init --recursive
cd /home/kduser/go/src/github.com/mattn/goreman
git show-ref
cd /home/kduser/go/src/github.com/mattn/goreman
git submodule update --init --recursive
cd /home/kduser/go/src/github.com/daviddengcn/go-colortext
git config remote.origin.url
github.com/daviddengcn/go-colortext (download)
cd /home/kduser/go/src/github.com/daviddengcn/go-colortext
git pull --ff-only
cd /home/kduser/go/src/github.com/daviddengcn/go-colortext
git submodule update --init --recursive
cd /home/kduser/go/src/github.com/daviddengcn/go-colortext
git show-ref
cd /home/kduser/go/src/github.com/daviddengcn/go-colortext
git submodule update --init --recursive
cd /home/kduser/go/src/github.com/joho/godotenv
git config remote.origin.url
github.com/joho/godotenv (download)
cd /home/kduser/go/src/github.com/joho/godotenv
git pull --ff-only
cd /home/kduser/go/src/github.com/joho/godotenv
git submodule update --init --recursive
cd /home/kduser/go/src/github.com/joho/godotenv
git show-ref
cd /home/kduser/go/src/github.com/joho/godotenv
git submodule update --init --recursive
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag main.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
cd .
git clone https://gopkg.in/yaml.v2 /home/kduser/go/src/gopkg.in/yaml.v2

same as your, it just hangs at this point. And the yaml.v2 directory is empty all the time. 
Yet, I can get goreman in my windows platform.
![out](https://cloud.githubusercontent.com/assets/17407521/17423196/98c94782-5aeb-11e6-8f7c-88f2de67f108.png)

**Comment by mattn** [comment] 2018-01-31 03:24
Anyway, this is not an issue of goreman. So closing.

**Closed by mattn** 2018-01-31 03:24 UTC
